### ISSUE TITLE
change format date dd-mm-yyyy

### ISSUE THREAD

**Issue by gitcoffee** [ridewn/vue-date-picker#1]

**Comment by smith153** [comment]
@gitcoffee 

I had a similar issue. I think adding formatting options, although purely up to the original author, would be extra work. You can add a filter though. This is how I am handling it:

```html
<input type="text" readonly v-on:focus="show_created_time = true" :value="created_time | format_date">
<date-picker v-on:close="show_created_time = false" v-if="show_created_time" v-model="created_time"></date-picker> 
```

And elsewhere:

```javascript
/*
  Turn '2016-1-31' into '01-31-2016'
 */
Vue.filter('format_date', function fmt(date = '') {
    let date_parts = date.match(/^(\d{4})-(\d+)-(\d+)(.*)$/);
    let year;
    let month;
    let day;

    if (date_parts) {
        year = ('00' + date_parts[1]).slice(-4);
        month = ('0' + date_parts[2]).slice(-2);
        day = ('0' + date_parts[3]).slice(-2);

        return month + '-' + day + '-' + year + date_parts[4];
    } else {
        return date;
    }
});
```

**Comment by trevorstacy** [comment]
I will look into adding a `format` option that will allow you to specify a format for the dates.

**Comment by smith153** [comment]
@ridewn  as another option, you could also add a 'formatter' prop that just takes a reference to a function as an argument. That would allow one to pass a personalized formatting function directly into the component. Though not sure if that is the "vue" way, but I've had to do stuff like that before. Just an idea.

**Comment by trevorstacy** [comment]
Thank you for the suggestion @smith153, that is exactly what I added, it makes the most sense as handling formatting is out of the scope of what I can do without adding dependencies.

@gitcoffee see commit bdd0d1a31874d5975ab1e580295cf7274f664947. A formatting prop has been added, I'll update the docs soon, but you can look at the last example to see how it works. Now all you have to do is define a function that will receive the date picker's date, and format it how you wish:

```
<date-picker :format="formatDate" ...>

...

formatDate (date) {
  return moment(date).format('DD-MM-YYYY')
}
```
The above code will change the date picker's default value (i.e. YYYY-MM-DD) to DD-MM-YYYY.
