### ISSUE TITLE
Having more than one date picker on the same page causes warnings

### ISSUE THREAD

**Issue by Coreusa** [ridewn/vue-date-picker#13]
Try putting two date pickers on the same page. The second date picker will complain once you open it up, yielding:

`[Vue warn]: Duplicate keys detected: 'day-'. This may cause an update error.`

Looking at the source, this is the culprit: https://github.com/ridewn/vue-date-picker/blob/master/src/DatePicker.vue#L79

Suggest this gets unique to avoid these warnings (i.e: Use a property to help mitigate such issues)

**Comment by ghost** [comment]
#17 
@ridewn it is my first PR to open source and I'm not sure if PR is made in a right way.
